name: APP_NAME
options:
  bundleIdPrefix: com.ORGANIZATION
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.38.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_USER_SCRIPT_SANDBOXING: true

targets:
  APP_NAME:
    type: application
    platform: iOS
    sources:
      - path: Sources/APP_NAME
    resources:
      - path: Resources
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ORGANIZATION.APP_NAME
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    dependencies: []

  APP_NAMETests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/APP_NAMETests
    dependencies:
      - target: APP_NAME
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.ORGANIZATION.APP_NAME.tests
        GENERATE_INFOPLIST_FILE: true
